from __future__ import annotations

import numpy as np

from voxel_world import CHUNK_SIZE

CHUNK_SAMPLE_SIZE = CHUNK_SIZE + 2
MAX_FACES_PER_CELL = 5
VERTICES_PER_FACE = 6
MAX_VERTICES_PER_CHUNK = CHUNK_SIZE * CHUNK_SIZE * MAX_FACES_PER_CELL * VERTICES_PER_FACE
VERTEX_STRIDE = 48
LIGHT_DIRECTION = (0.35, 0.90, 0.25)
DEPTH_FORMAT = "depth24plus"
ENGINE_MODE_CPU = "cpu"
ENGINE_MODE_WGPU = "wgpu"
ENGINE_MODE_METAL = "metal"
DEFAULT_RENDER_DISTANCE_BLOCKS = CHUNK_SIZE * 32
MERGED_TILE_SIZE_CHUNKS = 4
MERGED_TILE_MIN_AGE_SECONDS = 2.0
MERGED_TILE_MAX_CHUNKS = MERGED_TILE_SIZE_CHUNKS * MERGED_TILE_SIZE_CHUNKS
MAX_CACHED_CHUNKS = 4225
DEFAULT_MESH_BATCH_SIZE = 128
MESH_OUTPUT_SLAB_MIN_BYTES = 16 * 1024 * 1024
INDIRECT_DRAW_COMMAND_STRIDE = 16
GPU_VISIBILITY_WORKGROUP_SIZE = 64
MESH_OUTPUT_FREERANGE_SCAN_LIMIT = 4
MESH_OUTPUT_FREE_DELAY_FRAMES = 16
MESH_VISIBILITY_RECORD_DTYPE = np.dtype([("bounds", np.float32, 4), ("draw", np.uint32, 4)])
VOXEL_SURFACE_EXPAND_BIND_GROUP_CACHE_LIMIT = 2048
HUD_FONT_SCALE = 2
HUD_FONT_CHAR_WIDTH = 5
HUD_FONT_CHAR_HEIGHT = 9
HUD_PANEL_PADDING = 10
HUD_LINE_SPACING = 3
HUD_GLYPH_SPACING = 1
PROFILE_REPORT_INTERVAL = 1.0
FRAME_BREAKDOWN_SAMPLE_WINDOW = 120
SWAPCHAIN_MAX_FPS = 320
SWAPCHAIN_USE_VSYNC = False
SPRINT_FLY_SPEED = 1500.0
