from __future__ import annotations

import numpy as np

from .world_constants import (
    BLOCK_SIZE,
    CHUNK_SIZE,
    CHUNK_WORLD_SIZE,
    WORLD_HEIGHT_BLOCKS,
    VERTICAL_CHUNK_COUNT,
    VERTICAL_CHUNK_RENDER_RADIUS,
    VERTICAL_CHUNK_STACK_ENABLED,
)

CHUNK_SAMPLE_SIZE = CHUNK_SIZE + 2
MAX_FACES_PER_CELL = 5
VERTICES_PER_FACE = 6
MAX_VERTICES_PER_CHUNK = CHUNK_SIZE * CHUNK_SIZE * MAX_FACES_PER_CELL * VERTICES_PER_FACE
VERTEX_STRIDE = 48
LIGHT_DIRECTION = (0.35, 0.90, 0.25)
DEPTH_FORMAT = "depth24plus"
POSTPROCESS_SCENE_FORMAT = "rgba8unorm"
POSTPROCESS_OCCLUSION_FORMAT = "rgba8unorm"
POSTPROCESS_SHAFT_FORMAT = "rgba8unorm"
VOLUMETRIC_LIGHTING_ENABLED = True
VOLUMETRIC_LIGHTING_SAMPLES = 48
VOLUMETRIC_LIGHTING_DENSITY = 1.12
VOLUMETRIC_LIGHTING_WEIGHT = 0.05
VOLUMETRIC_LIGHTING_DECAY = 0.95
VOLUMETRIC_LIGHTING_EXPOSURE = 0.88
VOLUMETRIC_LIGHTING_STRENGTH = 0.2
ENGINE_MODE_CPU = "cpu"
ENGINE_MODE_WGPU = "wgpu"
ENGINE_MODE_METAL = "metal"
DEFAULT_RENDER_DISTANCE_CHUNKS = 16
DEFAULT_RENDER_DISTANCE_BLOCKS = CHUNK_SIZE * DEFAULT_RENDER_DISTANCE_CHUNKS
DEFAULT_RENDER_DISTANCE_WORLD = DEFAULT_RENDER_DISTANCE_BLOCKS * BLOCK_SIZE
MERGED_TILE_SIZE_CHUNKS = 4
MERGED_TILE_MIN_AGE_SECONDS = 2.0
MERGED_TILE_MAX_CHUNKS = MERGED_TILE_SIZE_CHUNKS * MERGED_TILE_SIZE_CHUNKS
def _visible_chunk_capacity() -> int:
    radius = int(DEFAULT_RENDER_DISTANCE_CHUNKS)
    horizontal = 0
    radius_sq = radius * radius
    for dz in range(-radius, radius + 1):
        for dx in range(-radius, radius + 1):
            if dx * dx + dz * dz <= radius_sq:
                horizontal += 1
    vertical_layers = (int(VERTICAL_CHUNK_RENDER_RADIUS) * 2 + 1) if VERTICAL_CHUNK_STACK_ENABLED else 1
    vertical_layers = max(1, min(int(VERTICAL_CHUNK_COUNT), int(vertical_layers)))
    return int(horizontal * vertical_layers)


MAX_CACHED_CHUNKS = _visible_chunk_capacity()
DEFAULT_MESH_BATCH_SIZE = 1 if WORLD_HEIGHT_BLOCKS > 256 else (16 if CHUNK_SIZE >= 64 else 128)
MESH_OUTPUT_SLAB_MIN_BYTES = (8 if WORLD_HEIGHT_BLOCKS > 256 else (16 if CHUNK_SIZE >= 64 else 64)) * 1024 * 1024
MESH_OUTPUT_UPLOAD_BATCH_BYTES = (8 if WORLD_HEIGHT_BLOCKS > 256 else (32 if CHUNK_SIZE >= 64 else 128)) * 1024 * 1024
METAL_MESH_INFLIGHT_SLOTS = 1 if WORLD_HEIGHT_BLOCKS > 256 else (2 if CHUNK_SIZE >= 64 else 3)
INDIRECT_DRAW_COMMAND_STRIDE = 16
GPU_VISIBILITY_WORKGROUP_SIZE = 64
MESH_OUTPUT_FREERANGE_SCAN_LIMIT = 16
MESH_OUTPUT_FREE_DELAY_FRAMES = 16
MESH_VISIBILITY_RECORD_DTYPE = np.dtype([("bounds", np.float32, 4), ("draw", np.uint32, 4)])
VOXEL_SURFACE_EXPAND_BIND_GROUP_CACHE_LIMIT = 2048
HUD_FONT_SCALE = 2
HUD_FONT_CHAR_WIDTH = 5
HUD_FONT_CHAR_HEIGHT = 9
HUD_PANEL_PADDING = 10
HUD_LINE_SPACING = 3
HUD_GLYPH_SPACING = 1
PROFILE_REPORT_INTERVAL = 1.0
FRAME_BREAKDOWN_SAMPLE_WINDOW = 120
SWAPCHAIN_MAX_FPS = 320
SWAPCHAIN_USE_VSYNC = False
BASE_FLY_SPEED = 4.5
SPRINT_FLY_SPEED = 200.0
WALK_SPRINT_SPEED = 9.0
PLAYER_COLLIDER_HALF_WIDTH_METERS = 0.30
PLAYER_COLLIDER_HEIGHT_METERS = 1.80
PLAYER_EYE_OFFSET_METERS = 1.62
PLAYER_STEP_HEIGHT_METERS = 0.45
PLAYER_JUMP_SPEED_METERS = 6.5
PLAYER_GRAVITY_METERS = 24.0
PLAYER_GROUND_SNAP_METERS = 0.55
CAMERA_EYE_HEIGHT_METERS = PLAYER_EYE_OFFSET_METERS
CAMERA_MIN_HEIGHT_METERS = 0.6
CAMERA_HEADROOM_METERS = 4.8
