from __future__ import annotations

import numpy as np

from .world_constants import (
    BLOCK_SIZE,
    CHUNK_SIZE,
    CHUNK_WORLD_SIZE,
    WORLD_HEIGHT_BLOCKS,
    VERTICAL_CHUNK_COUNT,
    VERTICAL_CHUNK_RENDER_RADIUS,
    VERTICAL_CHUNK_STACK_ENABLED,
)

CHUNK_SAMPLE_SIZE = CHUNK_SIZE + 2
MAX_FACES_PER_CELL = 5
VERTICES_PER_FACE = 6
MAX_VERTICES_PER_CHUNK = CHUNK_SIZE * CHUNK_SIZE * MAX_FACES_PER_CELL * VERTICES_PER_FACE
VERTEX_STRIDE = 48
LIGHT_DIRECTION = (0.35, 0.90, 0.25)
DEPTH_FORMAT = "depth24plus"
POSTPROCESS_SCENE_FORMAT = "rgba8unorm"
POSTPROCESS_GBUFFER_FORMAT = "rgba16float"
POSTPROCESS_GI_FORMAT = "rgba16float"
POSTPROCESS_COMPOSITE_FORMAT = "rgba8unorm"
POSTPROCESS_MSAA_SAMPLE_COUNT = 4
RADIANCE_CASCADES_ENABLED = True
RADIANCE_CASCADES_COMPOSE_SCALE = 1.0
RADIANCE_CASCADES_SKY_HORIZON_RGB = (0.58, 0.75, 0.96)
RADIANCE_CASCADES_SKY_ZENITH_RGB = (0.22, 0.46, 0.90)
RADIANCE_CASCADES_SKY_GROUND_RGB = (0.045, 0.055, 0.065)
RADIANCE_CASCADES_SKY_SUN_GLOW_RGB = (1.00, 0.82, 0.48)
RADIANCE_CASCADES_STRENGTH = 1.50
RADIANCE_CASCADES_BIAS = 0.12
RADIANCE_CASCADES_SKY_STRENGTH = 0.90
RADIANCE_CASCADES_HIT_THICKNESS = 0.45
RADIANCE_CASCADES_CASCADE_COUNT = 4
RADIANCE_CASCADES_BASE_INTERVAL = 0.75
RADIANCE_CASCADES_INTERVAL_SCALE = 2.0
RADIANCE_CASCADES_STEPS_PER_CASCADE = 3
RADIANCE_CASCADES_BASE_RAY_COUNT = 8
RADIANCE_CASCADES_RAY_COUNT_DECAY = 0.7
RADIANCE_CASCADES_MERGE_OVERLAP = 0.30
RADIANCE_CASCADES_MERGE_STRENGTH = 0.82
WORLDSPACE_RC_GRID_RESOLUTION = 16
WORLDSPACE_RC_DIRECTION_COUNT = 4
WORLDSPACE_RC_BASE_HALF_EXTENT_WORLD = CHUNK_WORLD_SIZE * 0.75
WORLDSPACE_RC_INTERVAL_SCALE = 2.0
WORLDSPACE_RC_TRACE_DIRECTIONS = 24
WORLDSPACE_RC_TRACE_MAX_STEPS = 14
WORLDSPACE_RC_UPDATE_QUANTIZE_WORLD = BLOCK_SIZE * 4.0
WORLDSPACE_RC_UPDATE_MAX_CASCADES_PER_FRAME = 4
WORLDSPACE_RC_INITIAL_MAX_CASCADES_PER_FRAME = 4
WORLDSPACE_RC_UPDATE_FRAME_INTERVAL = 1
WORLDSPACE_RC_SPARSE_UPDATE_ENABLED = True
WORLDSPACE_RC_CASCADE_PROBE_STRIDES = (1, 2, 2, 3)
WORLDSPACE_RC_DILATE_INVALID_PROBES = True
WORLDSPACE_RC_INVALID_PROBE_DILATE_MAX_GRID_DISTANCE = 8
WORLDSPACE_RC_INVALID_PROBE_DILATE_RADIANCE_SCALE = 0.20
WORLDSPACE_RC_MATERIAL_CACHE_MAX_ENTRIES = 200000
WORLDSPACE_RC_TEMPORAL_BLEND_ALPHA = 0.34
WORLDSPACE_RC_SPATIAL_FILTER_PASSES = 2
WORLDSPACE_RC_SPATIAL_FILTER_SKY_POWER = 2.10
WORLDSPACE_RC_SKY_VISIBILITY_STEPS = 96
WORLDSPACE_RC_SKY_VISIBILITY_STEP_BLOCKS = 1
WORLDSPACE_RC_SKY_VISIBILITY_SIDE_WEIGHT = 0.15
WORLDSPACE_RC_SKY_VISIBILITY_APERTURE_RADIUS_BLOCKS = 2
WORLDSPACE_RC_SKY_VISIBILITY_APERTURE_POWER = 2.25
WORLDSPACE_RC_SKY_VISIBILITY_MIN_APERTURE = 0.0
WORLDSPACE_RC_DIRECT_SUN_STRENGTH = 1.15
WORLDSPACE_RC_INDIRECT_FLOOR = 0.045
WORLDSPACE_RC_CAVE_MIN_LIGHT = 0.018
WORLDSPACE_RC_CAVE_SKY_POWER = 4.25
WORLDSPACE_RC_CAVE_DARKENING = 1.0
WORLDSPACE_RC_VISIBILITY_BIAS = BLOCK_SIZE * 1.10
WORLDSPACE_RC_VISIBILITY_VARIANCE_BIAS = (BLOCK_SIZE * 2.0) * (BLOCK_SIZE * 2.0)
WORLDSPACE_RC_VISIBILITY_SHARPNESS = 4.5
WORLDSPACE_RC_MIN_HIT_FRACTION = 0.18
WORLDSPACE_RC_BACKFACE_SOFTNESS = 0.18
WORLDSPACE_RC_CASCADE_BLEND_EDGE_START = 0.06
WORLDSPACE_RC_CASCADE_BLEND_EDGE_END = 0.18
WORLDSPACE_RC_CASCADE_BLEND_MIN_WEIGHT = 0.12
WORLDSPACE_RC_CASCADE_BLEND_CONFIDENCE_SCALE = 1.35
WORLDSPACE_RC_CASCADE_BLEND_FAR_BIAS = 0.55
ENGINE_MODE_CPU = "cpu"
ENGINE_MODE_WGPU = "wgpu"
ENGINE_MODE_METAL = "metal"
DEFAULT_RENDER_DISTANCE_CHUNKS = 8
DEFAULT_RENDER_DISTANCE_BLOCKS = CHUNK_SIZE * DEFAULT_RENDER_DISTANCE_CHUNKS
DEFAULT_RENDER_DISTANCE_WORLD = DEFAULT_RENDER_DISTANCE_BLOCKS * BLOCK_SIZE
MERGED_TILE_SIZE_CHUNKS = 4
MERGED_TILE_MIN_AGE_SECONDS = 2.0
MERGED_TILE_MAX_CHUNKS = MERGED_TILE_SIZE_CHUNKS * MERGED_TILE_SIZE_CHUNKS
def _visible_chunk_capacity() -> int:
    """Return the maximum valid visible-coordinate budget used by the renderer.

    The visible-layout builder walks a full XZ box, then clamps vertical layers to
    real world chunk indices for the current origin. Capacity therefore needs to
    track the largest world-valid box the renderer can ever emit, not the unclamped
    theoretical span.
    """
    horizontal_radius = max(1, int(DEFAULT_RENDER_DISTANCE_CHUNKS))
    horizontal_layers = horizontal_radius * 2 + 1
    horizontal = horizontal_layers * horizontal_layers
    requested_vertical_layers = (max(0, int(VERTICAL_CHUNK_RENDER_RADIUS)) * 2 + 1) if VERTICAL_CHUNK_STACK_ENABLED else 1
    vertical_layers = min(max(1, requested_vertical_layers), max(1, int(VERTICAL_CHUNK_COUNT)))
    return int(horizontal * vertical_layers)


MAX_CACHED_CHUNKS = _visible_chunk_capacity()
DEFAULT_MESH_BATCH_SIZE = 1 if WORLD_HEIGHT_BLOCKS > 256 else (16 if CHUNK_SIZE >= 64 else 128)
MESH_OUTPUT_SLAB_MIN_BYTES = (8 if WORLD_HEIGHT_BLOCKS > 256 else (16 if CHUNK_SIZE >= 64 else 64)) * 1024 * 1024
MESH_OUTPUT_UPLOAD_BATCH_BYTES = (8 if WORLD_HEIGHT_BLOCKS > 256 else (32 if CHUNK_SIZE >= 64 else 128)) * 1024 * 1024
METAL_MESH_INFLIGHT_SLOTS = 1 if WORLD_HEIGHT_BLOCKS > 256 else (2 if CHUNK_SIZE >= 64 else 3)
INDIRECT_DRAW_COMMAND_STRIDE = 16
GPU_VISIBILITY_WORKGROUP_SIZE = 64
MESH_OUTPUT_FREERANGE_SCAN_LIMIT = 16
MESH_OUTPUT_FREE_DELAY_FRAMES = 16
MESH_VISIBILITY_RECORD_DTYPE = np.dtype([("bounds", np.float32, 4), ("draw", np.uint32, 4)])
VOXEL_SURFACE_EXPAND_BIND_GROUP_CACHE_LIMIT = 2048
HUD_FONT_SCALE = 2
HUD_FONT_CHAR_WIDTH = 5
HUD_FONT_CHAR_HEIGHT = 9
HUD_PANEL_PADDING = 10
HUD_LINE_SPACING = 3
HUD_GLYPH_SPACING = 1
PROFILE_REPORT_INTERVAL = 1.0
FRAME_BREAKDOWN_SAMPLE_WINDOW = 120
SWAPCHAIN_MAX_FPS = 320
SWAPCHAIN_USE_VSYNC = False
BASE_FLY_SPEED = 4.5
SPRINT_FLY_SPEED = 200.0
WALK_SPRINT_SPEED = 9.0
PLAYER_COLLIDER_HALF_WIDTH_METERS = 0.30
PLAYER_COLLIDER_HEIGHT_METERS = 1.80
PLAYER_EYE_OFFSET_METERS = 1.62
PLAYER_STEP_HEIGHT_METERS = 0.45
PLAYER_JUMP_SPEED_METERS = 6.5
PLAYER_GRAVITY_METERS = 24.0
PLAYER_GROUND_SNAP_METERS = 0.55
CAMERA_EYE_HEIGHT_METERS = PLAYER_EYE_OFFSET_METERS
CAMERA_MIN_HEIGHT_METERS = 0.6
CAMERA_HEADROOM_METERS = 4.8
