from __future__ import annotations

CHUNK_SIZE = 64
BLOCK_SIZE = 0.1
WORLD_HEIGHT_BLOCKS = 2000
CHUNK_WORLD_SIZE = CHUNK_SIZE * BLOCK_SIZE
WORLD_HEIGHT_METERS = WORLD_HEIGHT_BLOCKS * BLOCK_SIZE

# Experimental stacked vertical chunks.
VERTICAL_CHUNK_STACK_ENABLED = True
VERTICAL_CHUNK_RENDER_RADIUS = 16
VERTICAL_CHUNK_COUNT = (WORLD_HEIGHT_BLOCKS + CHUNK_SIZE - 1) // CHUNK_SIZE
